apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopease-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | default "shopease.local" }}
      http:
        paths:
          # React Frontend (handles SPA routes)
          - path: {{ .Values.ingress.paths.frontend | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontendService.service.port | int }}
          # User Service
          - path: {{ .Values.ingress.paths.users | default "/users" }}
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.userService.service.port | int }}

          # Product service
          - path: {{ .Values.ingress.paths.products | default "/products" }}
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: {{ .Values.productService.service.port | int }}
          