apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shopease-rolebinding
subjects:
- kind: ServiceAccount
  name: shopease-sa
roleRef:
  kind: Role
  name: shopease-role
  apiGroup: rbac.authorization.k8s.io
